{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# All customer 'OrderQuantity'<br>\n",
    "In this file, all customer order quantities are predicted. Other files were predicting order quantities based on the customer."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: nbformat in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (5.10.4)\n",
      "Requirement already satisfied: pandas in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (2.2.3)\n",
      "Requirement already satisfied: numpy in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (2.0.2)\n",
      "Requirement already satisfied: matplotlib in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (3.10.1)\n",
      "Requirement already satisfied: seaborn in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (0.13.2)\n",
      "Requirement already satisfied: scikit-learn in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (1.6.1)\n",
      "Requirement already satisfied: xgboost in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (2.1.4)\n",
      "Requirement already satisfied: fastjsonschema>=2.15 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from nbformat) (2.21.1)\n",
      "Requirement already satisfied: jsonschema>=2.6 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from nbformat) (4.23.0)\n",
      "Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from nbformat) (5.7.2)\n",
      "Requirement already satisfied: traitlets>=5.1 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from nbformat) (5.14.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from pandas) (2025.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from pandas) (2025.1)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from matplotlib) (1.3.1)\n",
      "Requirement already satisfied: cycler>=0.10 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from matplotlib) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from matplotlib) (4.56.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from matplotlib) (1.4.8)\n",
      "Requirement already satisfied: packaging>=20.0 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from matplotlib) (24.2)\n",
      "Requirement already satisfied: pillow>=8 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from matplotlib) (11.1.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from matplotlib) (3.2.1)\n",
      "Requirement already satisfied: scipy>=1.6.0 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from scikit-learn) (1.15.2)\n",
      "Requirement already satisfied: joblib>=1.2.0 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from scikit-learn) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: attrs>=22.2.0 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from jsonschema>=2.6->nbformat) (25.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from jsonschema>=2.6->nbformat) (2024.10.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from jsonschema>=2.6->nbformat) (0.36.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from jsonschema>=2.6->nbformat) (0.23.1)\n",
      "Requirement already satisfied: platformdirs>=2.5 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.6)\n",
      "Requirement already satisfied: pywin32>=300 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (308)\n",
      "Requirement already satisfied: six>=1.5 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: typing-extensions>=4.4.0 in d:\\scm---ml-visualisation\\tf_env\\lib\\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.12.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3 -> 25.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "%pip install nbformat pandas numpy matplotlib seaborn scikit-learn xgboost"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.append('./../src')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the dataset\n",
    "product_sales_df = pd.read_csv('../datasets/forecasting/final/product_sales.csv')\n",
    "\n",
    "# Reducing df size due to issues with not enough system hardware for hyperparam training\n",
    "fraction = 0.30\n",
    "\n",
    "# Randomly sample the DataFrame\n",
    "product_sales_df = product_sales_df.sample(frac=fraction, random_state=42)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Z-score removal\n",
    "This feature is controversial. In SCM, volitility is inevitable and the model SHOULD be trained to handle this. It can also skew all predictions making all predictions inaccurate, where as if these are removed predictions for OrderQuantity could be more accurate.\n",
    "\n",
    "__If wanting to keep the abnormally high OrderQuantity values, COMMENT THIS OUT!__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:7: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.\n",
      "  group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unusually high order quantities (per ProductNumber):\n",
      "                     ProductNumber  OrderQuantity   z_score\n",
      "ProductNumber                                              \n",
      "FRE-005-0049Z 11903  FRE-005-0049Z         720000  3.032564\n",
      "UND-026-0086Z 48616  UND-026-0086Z         720000  3.361733\n",
      "UND-026-0092Y 48792  UND-026-0092Y         204000  3.085499\n",
      "Dropping: \n",
      "ProductNumber         3\n",
      "order_year            3\n",
      "order_month           3\n",
      "order_week            3\n",
      "order_weekday         3\n",
      "is_weekend            3\n",
      "Customer_Num          3\n",
      "OrderQuantity         3\n",
      "prev_month_sales      3\n",
      "prev_week_sales       3\n",
      "prev_2_month_sales    3\n",
      "prev_3_month_sales    3\n",
      "var_1m                0\n",
      "var_3m                3\n",
      "var_6m                3\n",
      "var_12m               3\n",
      "var_18m               3\n",
      "log_var_1m            0\n",
      "log_var_3m            3\n",
      "log_var_6m            3\n",
      "log_var_12m           3\n",
      "log_var_18m           3\n",
      "yoy_growth            3\n",
      "moving_avg_3m         3\n",
      "moving_avg_6m         3\n",
      "moving_avg_12m        3\n",
      "moving_avg_18m        3\n",
      "sales_2022            3\n",
      "sales_2023            3\n",
      "sales_2024            3\n",
      "growth_2023           2\n",
      "growth_2024           2\n",
      "PhysicalInv           3\n",
      "z_score               3\n",
      "dtype: int64\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\1902335139.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "  df_grouped = product_sales_df.groupby('ProductNumber').apply(compute_zscore)\n"
     ]
    }
   ],
   "source": [
    "from scipy import stats\n",
    "\n",
    "# Define a function to compute z-scores within each product group\n",
    "def compute_zscore(group, threshold=3):\n",
    "    # Only compute z-score if there are at least 2 data points in the group\n",
    "    if len(group) >= 2:\n",
    "        group['z_score'] = np.abs(stats.zscore(group['OrderQuantity']))\n",
    "    else:\n",
    "        group['z_score'] = 0  # or np.nan if preferred\n",
    "    return group\n",
    "\n",
    "# Group by \"ProductNumber\" and compute z-scores for \"OrderQuantity\" within each group\n",
    "df_grouped = product_sales_df.groupby('ProductNumber').apply(compute_zscore)\n",
    "\n",
    "# Define your threshold for what constitutes an \"unusually high\" order\n",
    "z_threshold = 3\n",
    "\n",
    "# Filter for outliers (orders with a z_score greater than the threshold)\n",
    "df_outliers = df_grouped[df_grouped['z_score'] > z_threshold]\n",
    "\n",
    "# Display the results\n",
    "print(\"Unusually high order quantities (per ProductNumber):\")\n",
    "print(df_outliers[['ProductNumber', 'OrderQuantity', 'z_score']])\n",
    "\n",
    "print(f'Dropping: \\n{df_outliers.count()}')\n",
    "# Keep only rows where the z-score is within the acceptable range\n",
    "df_cleaned = df_grouped[df_grouped['z_score'] <= z_threshold].drop(columns=['z_score'])\n",
    "\n",
    "# Reset index for clarity\n",
    "df_cleaned.reset_index(drop=True, inplace=True)\n",
    "\n",
    "product_sales_df = df_cleaned"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.preprocessing import OneHotEncoder\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.neural_network import MLPRegressor\n",
    "from xgboost import XGBRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\44777\\AppData\\Local\\Temp\\ipykernel_10632\\2881775782.py:23: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  X['ProductNumber'] = X['ProductNumber'].astype(str)\n"
     ]
    }
   ],
   "source": [
    "features = ['ProductNumber', 'order_month',\n",
    "            'prev_month_sales', 'prev_week_sales', 'prev_2_month_sales', 'prev_3_month_sales',\n",
    "            'moving_avg_3m', 'moving_avg_6m', 'moving_avg_12m', 'moving_avg_18m',\n",
    "            'var_3m', 'var_6m', 'var_12m', 'var_18m',\n",
    "            'log_var_3m', 'log_var_6m', 'log_var_12m', 'log_var_18m',\n",
    "            'yoy_growth', 'sales_2023', 'sales_2024'\n",
    "            ]\n",
    "target = 'OrderQuantity'\n",
    "\n",
    "X = product_sales_df[features]\n",
    "y = product_sales_df[target]\n",
    "\n",
    "# define categorical and numeric features\n",
    "categorical_features = ['ProductNumber']\n",
    "numeric_features = list(set(features) - set(categorical_features))  # All other features are numeric\n",
    "# ensure ProductNumber is categorical\n",
    "product_sales_df['ProductNumber'] = product_sales_df['ProductNumber'].astype(str)\n",
    "\n",
    "# one-hot encoding for categorical features\n",
    "encoder = OneHotEncoder(handle_unknown='error', sparse_output=False)\n",
    "\n",
    "# Check/convert 'ProductNumber' to string before fitting OneHotEncoder\n",
    "X['ProductNumber'] = X['ProductNumber'].astype(str)\n",
    "\n",
    "# Preprocessing pipeline\n",
    "categorical_transformer = Pipeline(steps=[\n",
    "    ('imputer', SimpleImputer(strategy='most_frequent')),\n",
    "    ('encoder', OneHotEncoder(handle_unknown='error', sparse_output=False))\n",
    "])\n",
    "\n",
    "numeric_transformer = Pipeline(steps=[\n",
    "    ('imputer', SimpleImputer(strategy='mean')),\n",
    "    ('scaler', StandardScaler())\n",
    "])\n",
    "\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('cat', categorical_transformer, categorical_features),\n",
    "        ('num', numeric_transformer, numeric_features)\n",
    "    ]\n",
    ")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_preprocessed = preprocessor.fit_transform(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train, X_val, y_train, y_val = train_test_split(X_preprocessed, y, test_size=0.2, random_state=42)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Random Forest Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model type: RandomForestRegressor\n",
      "Fitting 5 folds for each of 108 candidates, totalling 540 fits\n"
     ]
    }
   ],
   "source": [
    "from model_utils import *\n",
    "\n",
    "# train the model with features (Random Forest Regressor)\n",
    "rf_params = find_best_hyperparameters(RandomForestRegressor(), param_grids(RandomForestRegressor().__class__.__name__), X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "rf_tuned = RandomForestRegressor(**rf_params)\n",
    "\n",
    "rf_tuned.fit(X_train, y_train)\n",
    "rf_y_pred = rf_tuned.predict(y_val)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print('---------------------- TRAINING PERFORMANCE ----------------------')\n",
    "evaluate_model(rf_tuned, X_train, y_train)\n",
    "print('--------------------------------------------')\n",
    "\n",
    "print('---------------------- TEST PERFORMANCE ----------------------')\n",
    "evaluate_model(rf_tuned, X_val, y_val)\n",
    "print('--------------------------------------------')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Neural Network Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "mlp_params = find_best_hyperparameters(MLPRegressor(), param_grids(MLPRegressor().__name__), X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "mlp_tuned = MLPRegressor(**mlp_params)\n",
    "\n",
    "mlp_tuned.fit(X_train, y_train)\n",
    "mlp_y_pred = mlp_tuned.predict(y_val)\n",
    "\n",
    "# Evaluate model using the imported function\n",
    "print('---------------------- TRAINING PERFORMANCE ----------------------')\n",
    "train_metrics = evaluate_model(mlp_tuned, X_train, y_train)\n",
    "print('--------------------------------------------')\n",
    "print('---------------------- TEST PERFORMANCE ----------------------')\n",
    "test_metrics = evaluate_model(mlp_tuned, X_val, y_val)\n",
    "print('--------------------------------------------')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### XGBoost Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "xgb_params = find_best_hyperparameters(XGBRegressor(), param_grids(XGBRegressor().__name__), X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "xgb_tuned = XGBRegressor(**xgb_params)\n",
    "\n",
    "xgb_tuned.fit(X_train, y_train)\n",
    "xgb_y_pred = xgb_tuned.predict(y_val)\n",
    "\n",
    "# Evaluate model using the imported function\n",
    "print('---------------------- TRAINING PERFORMANCE ----------------------')\n",
    "train_metrics = evaluate_model(xgb_tuned, X_train, y_train)\n",
    "print('--------------------------------------------')\n",
    "print('---------------------- TEST PERFORMANCE ----------------------')\n",
    "test_metrics = evaluate_model(xgb_tuned, X_val, y_val)\n",
    "print('--------------------------------------------')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a DetailedOrderDate column using week and weekday information.\n",
    "# Adjust the format as needed based on your data.\n",
    "product_sales_df['DetailedOrderDate'] = pd.to_datetime(\n",
    "    product_sales_df['order_year'].astype(str) +\n",
    "    product_sales_df['order_week'].astype(str).str.zfill(2) +\n",
    "    product_sales_df['order_weekday'].astype(str),\n",
    "    format='%Y%W%w'\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Convert order year and month to datetime format\n",
    "product_sales_df['OrderDate'] = pd.to_datetime(product_sales_df[['order_year', 'order_month']].astype(str).agg('-'.join, axis=1))\n",
    "\n",
    "# Sort by OrderDate to maintain time order\n",
    "product_sales_df = product_sales_df.sort_values(by='OrderDate')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Plotting Model Results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create subplots (2 rows, 2 columns: one for line plot, one for residual plot)\n",
    "fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(18, 12)) \n",
    "fig.subplots_adjust(hspace=0.5, wspace=0.4)\n",
    "\n",
    "# Time Series Comparison\n",
    "sns.lineplot(x=product_sales_df.loc[y_val.index, 'OrderDate'], y=y_val, label='Actual', ax=axes[0, 0])\n",
    "sns.lineplot(x=product_sales_df.loc[y_val.index, 'OrderDate'], y=rf_y_pred, label='Predicted', ax=axes[0, 0])\n",
    "axes[0, 0].set_title(f'Random Forest - Time Series', fontsize=16)\n",
    "axes[0, 0].set_xlabel('Date', fontsize=14)  \n",
    "axes[0, 0].set_ylabel('Order Quantity', fontsize=14)\n",
    "\n",
    "# Residual Plot\n",
    "residuals = y_val - rf_y_pred\n",
    "sns.scatterplot(x=rf_y_pred, y=residuals, alpha=0.6, ax=axes[0, 1])\n",
    "axes[0, 1].axhline(0, color='r', linestyle='--')\n",
    "axes[0, 1].set_title(f'Random Forest - Residuals', fontsize=16)  \n",
    "axes[0, 1].set_xlabel('Predicted Values', fontsize=14)  \n",
    "axes[0, 1].set_ylabel('Scaled Residuals', fontsize=14)\n",
    "\n",
    "# Actual vs Predicted Scatter Plot\n",
    "min_val = min(y_val.min(), rf_y_pred.min())\n",
    "max_val = max(y_val.max(), rf_y_pred.max())\n",
    "sns.scatterplot(x=y_val, y=rf_y_pred, alpha=0.6, ax=axes[0, 2], label='Predicted')\n",
    "axes[0, 2].plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=1)  # Reference line\n",
    "axes[0, 2].set_title(f'Random Forest - Accuracy', fontsize=16)\n",
    "axes[0, 2].set_xlabel('Actual Values', fontsize=14)\n",
    "axes[0, 2].set_ylabel('Predicted Values', fontsize=14)  \n",
    "axes[0, 2].legend(fontsize=12)\n",
    "\n",
    "# Adjust x-tick labels after all plots are drawn\n",
    "plt.setp(axes[0, 0].get_xticklabels(), rotation=45, ha='right', fontsize=12)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "# Create subplots\n",
    "fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(18, 10))\n",
    "fig.subplots_adjust(hspace=0.4, wspace=0.3)\n",
    "\n",
    "# Bar plot: Actual vs. Predicted\n",
    "axes[0, 0].bar(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    y_val, \n",
    "    label='Actual', \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 0].bar(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    rf_y_pred, \n",
    "    label='Predicted', \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 0].set_xlabel('Order Date')\n",
    "axes[0, 0].set_ylabel('Order Quantity')\n",
    "axes[0, 0].set_title(f'{custom_ref} Total Products - Actual vs Predicted (Bar Plot)')\n",
    "axes[0, 0].set_ylim(0, 1_000_000)\n",
    "axes[0, 0].legend()\n",
    "axes[0, 0].tick_params(axis='x', rotation=45)\n",
    "\n",
    "# Residual Plot\n",
    "residuals = y_val - rf_y_pred\n",
    "axes[0, 1].scatter(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    residuals, \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 1].axhline(y=0, color='r', linestyle='--')\n",
    "axes[0, 1].set_xlabel('Order Date')\n",
    "axes[0, 1].set_ylabel('Residuals')\n",
    "axes[0, 1].set_title(f'Total Products - Residual Plot')\n",
    "axes[0, 1].tick_params(axis='x', rotation=45)\n",
    "\n",
    "# Pie Chart: Order Quantity Distribution (2024)\n",
    "order_2024 = product_sales_df[product_sales_df['order_year'] == 2024] \\\n",
    "    .groupby('order_month')['OrderQuantity'].sum()\n",
    "axes[0, 2].pie(\n",
    "    order_2024,\n",
    "    labels=order_2024.index,\n",
    "    autopct='%1.1f%%',\n",
    "    startangle=90,\n",
    "    colors=plt.cm.Paired.colors\n",
    ")\n",
    "axes[0, 2].set_title(f'{custom_ref} Order Quantity Distribution (2024)')\n",
    "\n",
    "# Line Plots: Yearly Trends\n",
    "for i, year in enumerate([2022, 2023, 2024]):  \n",
    "    yearly_df = product_sales_df[product_sales_df['order_year'] == year]\n",
    "    if yearly_df.empty:\n",
    "        continue\n",
    "\n",
    "    # Aggregate OrderQuantity per month\n",
    "    monthly_actual = yearly_df.groupby('order_month')['OrderQuantity'].sum()\n",
    "\n",
    "    # Convert to Pandas Series with index from product_sales_df\n",
    "    pred_series = pd.Series(rf_y_pred, index=y_val.index)\n",
    "\n",
    "    # Group predictions by month\n",
    "    monthly_predicted = pred_series.groupby(product_sales_df.loc[y_val.index, 'order_month']).sum()\n",
    "\n",
    "    # Sort for proper plotting\n",
    "    monthly_actual = monthly_actual.sort_index()\n",
    "    monthly_predicted = monthly_predicted.reindex(monthly_actual.index)  # Ensure same months\n",
    "\n",
    "    # Plot\n",
    "    axes[1, i].plot(\n",
    "        monthly_actual.index,\n",
    "        monthly_actual,\n",
    "        label='Actual',\n",
    "        alpha=0.6,\n",
    "        marker='o',\n",
    "        linestyle='-'\n",
    "    )\n",
    "    axes[1, i].plot(\n",
    "        monthly_predicted.index,\n",
    "        monthly_predicted,\n",
    "        label='Predicted',\n",
    "        alpha=0.6,\n",
    "        marker='x',\n",
    "        linestyle='--'\n",
    "    )\n",
    "    axes[1, i].set_xlabel('Month')\n",
    "    axes[1, i].set_ylabel('Order Quantity')\n",
    "    axes[1, i].set_title(f'{year} Total Products - Actual vs Predicted')\n",
    "    axes[1, i].set_ylim(0, max(monthly_actual.max(), monthly_predicted.max()) * 1.1)\n",
    "    axes[1, i].legend()\n",
    "    axes[1, i].tick_params(axis='x', rotation=45)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create subplots (2 rows, 2 columns: one for line plot, one for residual plot)\n",
    "fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(18, 12)) \n",
    "fig.subplots_adjust(hspace=0.5, wspace=0.4)\n",
    "\n",
    "# Time Series Comparison\n",
    "sns.lineplot(x=product_sales_df.loc[y_val.index, 'OrderDate'], y=y_val, label='Actual', ax=axes[0, 0])\n",
    "sns.lineplot(x=product_sales_df.loc[y_val.index, 'OrderDate'], y=mlp_y_pred, label='Predicted', ax=axes[0, 0])\n",
    "axes[0, 0].set_title(f'Neural Network (MLP) - Time Series', fontsize=16)\n",
    "axes[0, 0].set_xlabel('Date', fontsize=14)  \n",
    "axes[0, 0].set_ylabel('Order Quantity', fontsize=14)\n",
    "\n",
    "# Residual Plot\n",
    "residuals = y_val - mlp_y_pred\n",
    "sns.scatterplot(x=mlp_y_pred, y=residuals, alpha=0.6, ax=axes[0, 1])\n",
    "axes[0, 1].axhline(0, color='r', linestyle='--')\n",
    "axes[0, 1].set_title(f'Neural Network (MLP) - Residuals', fontsize=16)  \n",
    "axes[0, 1].set_xlabel('Predicted Values', fontsize=14)  \n",
    "axes[0, 1].set_ylabel('Scaled Residuals', fontsize=14)\n",
    "\n",
    "# Actual vs Predicted Scatter Plot\n",
    "min_val = min(y_val.min(), mlp_y_pred.min())\n",
    "max_val = max(y_val.max(), mlp_y_pred.max())\n",
    "sns.scatterplot(x=y_val, y=mlp_y_pred, alpha=0.6, ax=axes[0, 2], label='Predicted')\n",
    "axes[0, 2].plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=1)  # Reference line\n",
    "axes[0, 2].set_title(f'Neural Network (MLP) - Accuracy', fontsize=16)\n",
    "axes[0, 2].set_xlabel('Actual Values', fontsize=14)\n",
    "axes[0, 2].set_ylabel('Predicted Values', fontsize=14)  \n",
    "axes[0, 2].legend(fontsize=12)\n",
    "\n",
    "# Adjust x-tick labels after all plots are drawn\n",
    "plt.setp(axes[0, 0].get_xticklabels(), rotation=45, ha='right', fontsize=12)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create subplots\n",
    "fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(18, 10))\n",
    "fig.subplots_adjust(hspace=0.4, wspace=0.3)\n",
    "\n",
    "# Bar plot: Actual vs. Predicted\n",
    "axes[0, 0].bar(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    y_val, \n",
    "    label='Actual', \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 0].bar(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    mlp_y_pred, \n",
    "    label='Predicted', \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 0].set_xlabel('Order Date')\n",
    "axes[0, 0].set_ylabel('Order Quantity')\n",
    "axes[0, 0].set_title(f'{custom_ref} Total Products - Actual vs Predicted (Bar Plot)')\n",
    "axes[0, 0].set_ylim(0, 1_000_000)\n",
    "axes[0, 0].legend()\n",
    "axes[0, 0].tick_params(axis='x', rotation=45)\n",
    "\n",
    "# Residual Plot\n",
    "residuals = y_val - mlp_y_pred\n",
    "axes[0, 1].scatter(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    residuals, \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 1].axhline(y=0, color='r', linestyle='--')\n",
    "axes[0, 1].set_xlabel('Order Date')\n",
    "axes[0, 1].set_ylabel('Residuals')\n",
    "axes[0, 1].set_title(f'Total Products - Residual Plot')\n",
    "axes[0, 1].tick_params(axis='x', rotation=45)\n",
    "\n",
    "# Pie Chart: Order Quantity Distribution (2024)\n",
    "order_2024 = product_sales_df[product_sales_df['order_year'] == 2024] \\\n",
    "    .groupby('order_month')['OrderQuantity'].sum()\n",
    "axes[0, 2].pie(\n",
    "    order_2024,\n",
    "    labels=order_2024.index,\n",
    "    autopct='%1.1f%%',\n",
    "    startangle=90,\n",
    "    colors=plt.cm.Paired.colors\n",
    ")\n",
    "axes[0, 2].set_title(f'{custom_ref} Order Quantity Distribution (2024)')\n",
    "\n",
    "# Line Plots: Yearly Trends\n",
    "for i, year in enumerate([2022, 2023, 2024]):  \n",
    "    yearly_df = product_sales_df[product_sales_df['order_year'] == year]\n",
    "    if yearly_df.empty:\n",
    "        continue\n",
    "\n",
    "    # Aggregate OrderQuantity per month\n",
    "    monthly_actual = yearly_df.groupby('order_month')['OrderQuantity'].sum()\n",
    "\n",
    "    # Convert to Pandas Series with index from product_sales_df\n",
    "    pred_series = pd.Series(mlp_y_pred, index=y_val.index)\n",
    "\n",
    "    # Group predictions by month\n",
    "    monthly_predicted = pred_series.groupby(product_sales_df.loc[y_val.index, 'order_month']).sum()\n",
    "\n",
    "    # Sort for proper plotting\n",
    "    monthly_actual = monthly_actual.sort_index()\n",
    "    monthly_predicted = monthly_predicted.reindex(monthly_actual.index)  # Ensure same months\n",
    "\n",
    "    # Plot\n",
    "    axes[1, i].plot(\n",
    "        monthly_actual.index,\n",
    "        monthly_actual,\n",
    "        label='Actual',\n",
    "        alpha=0.6,\n",
    "        marker='o',\n",
    "        linestyle='-'\n",
    "    )\n",
    "    axes[1, i].plot(\n",
    "        monthly_predicted.index,\n",
    "        monthly_predicted,\n",
    "        label='Predicted',\n",
    "        alpha=0.6,\n",
    "        marker='x',\n",
    "        linestyle='--'\n",
    "    )\n",
    "    axes[1, i].set_xlabel('Month')\n",
    "    axes[1, i].set_ylabel('Order Quantity')\n",
    "    axes[1, i].set_title(f'{year} Total Products - Actual vs Predicted')\n",
    "    axes[1, i].set_ylim(0, max(monthly_actual.max(), monthly_predicted.max()) * 1.1)\n",
    "    axes[1, i].legend()\n",
    "    axes[1, i].tick_params(axis='x', rotation=45)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create subplots (2 rows, 2 columns: one for line plot, one for residual plot)\n",
    "fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(18, 12)) \n",
    "fig.subplots_adjust(hspace=0.5, wspace=0.4)\n",
    "\n",
    "# Time Series Comparison\n",
    "sns.lineplot(x=product_sales_df.loc[y_val.index, 'OrderDate'], y=y_val, label='Actual', ax=axes[0, 0])\n",
    "sns.lineplot(x=product_sales_df.loc[y_val.index, 'OrderDate'], y=xgb_y_pred, label='Predicted', ax=axes[0, 0])\n",
    "axes[0, 0].set_title(f'XGBoost - Time Series', fontsize=16)\n",
    "axes[0, 0].set_xlabel('Date', fontsize=14)  \n",
    "axes[0, 0].set_ylabel('Order Quantity', fontsize=14)\n",
    "\n",
    "# Residual Plot\n",
    "residuals = y_val - xgb_y_pred\n",
    "sns.scatterplot(x=xgb_y_pred, y=residuals, alpha=0.6, ax=axes[0, 1])\n",
    "axes[0, 1].axhline(0, color='r', linestyle='--')\n",
    "axes[0, 1].set_title(f'XGBoost - Residuals', fontsize=16)  \n",
    "axes[0, 1].set_xlabel('Predicted Values', fontsize=14)  \n",
    "axes[0, 1].set_ylabel('Scaled Residuals', fontsize=14)\n",
    "\n",
    "# Actual vs Predicted Scatter Plot\n",
    "min_val = min(y_val.min(), xgb_y_pred.min())\n",
    "max_val = max(y_val.max(), xgb_y_pred.max())\n",
    "sns.scatterplot(x=y_val, y=xgb_y_pred, alpha=0.6, ax=axes[0, 2], label='Predicted')\n",
    "axes[0, 2].plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=1)  # Reference line\n",
    "axes[0, 2].set_title(f'XGBoost - Accuracy', fontsize=16)\n",
    "axes[0, 2].set_xlabel('Actual Values', fontsize=14)\n",
    "axes[0, 2].set_ylabel('Predicted Values', fontsize=14)  \n",
    "axes[0, 2].legend(fontsize=12)\n",
    "\n",
    "# Adjust x-tick labels after all plots are drawn\n",
    "plt.setp(axes[0, 0].get_xticklabels(), rotation=45, ha='right', fontsize=12)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create subplots\n",
    "fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(18, 10))\n",
    "fig.subplots_adjust(hspace=0.4, wspace=0.3)\n",
    "\n",
    "# Bar plot: Actual vs. Predicted\n",
    "axes[0, 0].bar(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    y_val, \n",
    "    label='Actual', \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 0].bar(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    xgb_y_pred, \n",
    "    label='Predicted', \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 0].set_xlabel('Order Date')\n",
    "axes[0, 0].set_ylabel('Order Quantity')\n",
    "axes[0, 0].set_title(f'{custom_ref} Total Products - Actual vs Predicted (Bar Plot)')\n",
    "axes[0, 0].set_ylim(0, 1_000_000)\n",
    "axes[0, 0].legend()\n",
    "axes[0, 0].tick_params(axis='x', rotation=45)\n",
    "\n",
    "# Residual Plot\n",
    "residuals = y_val - xgb_y_pred\n",
    "axes[0, 1].scatter(\n",
    "    product_sales_df.loc[X_val.index, 'OrderDate'], \n",
    "    residuals, \n",
    "    alpha=0.6\n",
    ")\n",
    "axes[0, 1].axhline(y=0, color='r', linestyle='--')\n",
    "axes[0, 1].set_xlabel('Order Date')\n",
    "axes[0, 1].set_ylabel('Residuals')\n",
    "axes[0, 1].set_title(f'Total Products - Residual Plot')\n",
    "axes[0, 1].tick_params(axis='x', rotation=45)\n",
    "\n",
    "# Pie Chart: Order Quantity Distribution (2024)\n",
    "order_2024 = product_sales_df[product_sales_df['order_year'] == 2024] \\\n",
    "    .groupby('order_month')['OrderQuantity'].sum()\n",
    "axes[0, 2].pie(\n",
    "    order_2024,\n",
    "    labels=order_2024.index,\n",
    "    autopct='%1.1f%%',\n",
    "    startangle=90,\n",
    "    colors=plt.cm.Paired.colors\n",
    ")\n",
    "axes[0, 2].set_title(f'{custom_ref} Order Quantity Distribution (2024)')\n",
    "\n",
    "# Line Plots: Yearly Trends\n",
    "for i, year in enumerate([2022, 2023, 2024]):  \n",
    "    yearly_df = product_sales_df[product_sales_df['order_year'] == year]\n",
    "    if yearly_df.empty:\n",
    "        continue\n",
    "\n",
    "    # Aggregate OrderQuantity per month\n",
    "    monthly_actual = yearly_df.groupby('order_month')['OrderQuantity'].sum()\n",
    "\n",
    "    # Convert to Pandas Series with index from product_sales_df\n",
    "    pred_series = pd.Series(xgb_y_pred, index=y_val.index)\n",
    "\n",
    "    # Group predictions by month\n",
    "    monthly_predicted = pred_series.groupby(product_sales_df.loc[y_val.index, 'order_month']).sum()\n",
    "\n",
    "    # Sort for proper plotting\n",
    "    monthly_actual = monthly_actual.sort_index()\n",
    "    monthly_predicted = monthly_predicted.reindex(monthly_actual.index)  # Ensure same months\n",
    "\n",
    "    # Plot\n",
    "    axes[1, i].plot(\n",
    "        monthly_actual.index,\n",
    "        monthly_actual,\n",
    "        label='Actual',\n",
    "        alpha=0.6,\n",
    "        marker='o',\n",
    "        linestyle='-'\n",
    "    )\n",
    "    axes[1, i].plot(\n",
    "        monthly_predicted.index,\n",
    "        monthly_predicted,\n",
    "        label='Predicted',\n",
    "        alpha=0.6,\n",
    "        marker='x',\n",
    "        linestyle='--'\n",
    "    )\n",
    "    axes[1, i].set_xlabel('Month')\n",
    "    axes[1, i].set_ylabel('Order Quantity')\n",
    "    axes[1, i].set_title(f'{year} Total Products - Actual vs Predicted')\n",
    "    axes[1, i].set_ylim(0, max(monthly_actual.max(), monthly_predicted.max()) * 1.1)\n",
    "    axes[1, i].legend()\n",
    "    axes[1, i].tick_params(axis='x', rotation=45)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "tf_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
